MVCUI/Models/TeamMVCModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace MVCUI.Models
{
    public class TeamMVCModel
    {
        [Display(Name = "Team Name")]
        [StringLength(100, MinimumLength = 2)]
        [Required]
        public string TeamName { get; set; }
    
        [Display(Name = "Team Member List")]
        public List<SelectListItem> TeamMembers { get; set; } = new List<SelectListItem>();

        public List<string> SelectedTeamMembers { get; set; } = new List<string>();
    }
}

MVCUI/Models/TournamentMVCModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace MVCUI.Models
{
    public class TournamentMVCModel
    {
        [Display(Name = "Tournament Name")]
        [StringLength(100, MinimumLength = 3)]
        [Required]
        public string TournamentName { get; set; }

        [Display(Name = "Entry Fee")]
        [Range(0, double.MaxValue)]
        [DataType(DataType.Currency)]
        [Required]
        public decimal EntryFee { get; set; }

        [Display(Name = "Entered Teams")]
        public List<SelectListItem> EnteredTeams { get; set; } = new List<SelectListItem>();

        public List<string> SelectedEnteredTeams { get; set; } = new List<string>();

        [Display(Name = "Prizes")]
        public List<SelectListItem> Prizes { get; set; } = new List<SelectListItem>();

        public List<string> SelectedPrizes { get; set; } = new List<string>();
    }
}

MVCUI/Controllers/HomeController.cs
using System.Web.Mvc;
using TrackerLibrary;

namespace MVCUI.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            var tournaments = GlobalConfig.Connection.GetAllTournaments();
            return View(tournaments);
        }
    }
}

MVCUI/Controllers/PeopleController.cs
using System.Web.Mvc;
using TrackerLibrary;
using TrackerLibrary.Models;

namespace MVCUI.Controllers
{
    public class PeopleController : Controller
    {
        public ActionResult Index()
        {
            var availablePeople = GlobalConfig.Connection.GetAllPeople();
            return View(availablePeople);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(PersonModel person)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    GlobalConfig.Connection.CreatePerson(person);

                    return RedirectToAction(nameof(Index)); 
                }
                else
                {
                    return View();
                }
            }
            catch
            {
                return View();
            }
        }
    }
}

MVCUI/Controllers/PrizesController.cs
using System.Web.Mvc;
using TrackerLibrary;
using TrackerLibrary.Models;

namespace MVCUI.Controllers
{
    public class PrizesController : Controller
    {
        public ActionResult Index()
        {
            var prizes = GlobalConfig.Connection.GetAllPrizes();
            return View(prizes);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(PrizeModel prize)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    GlobalConfig.Connection.CreatePrize(prize);

                    return RedirectToAction(nameof(Index));
                }

                return View();
            }
            catch
            {
                return View();
            }
        }
    }
}

MVCUI/Controllers/TeamsController.cs
using MVCUI.Models;
using System.Linq;
using System.Web.Mvc;
using TrackerLibrary;
using TrackerLibrary.Models;

namespace MVCUI.Controllers
{
    public class TeamsController : Controller
    {
        public ActionResult Index()
        {
            var teams = GlobalConfig.Connection.GetAllTeams();
            return View(teams);
        }

        public ActionResult Create()
        {
            var people = GlobalConfig.Connection.GetAllPeople();

            TeamMVCModel input = new TeamMVCModel()
            {
                TeamMembers = people.Select(p => new SelectListItem()
                {
                    Value = p.Id.ToString(),
                    Text = p.FullName
                }).ToList()
            };

            return View(input);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(TeamMVCModel teamMVC)
        {
            try
            {
                if (teamMVC.SelectedTeamMembers.Count <= 0)
                {
                    ModelState.AddModelError(nameof(teamMVC.SelectedTeamMembers.Count), "Invalid selected team members count");
                }

                if (ModelState.IsValid)
                {
                    TeamModel team = new TeamModel()
                    {
                        TeamName = teamMVC.TeamName,
                        TeamMembers = teamMVC.SelectedTeamMembers.Select(t => new PersonModel { Id = int.Parse(t) }).ToList()
                    };

                    GlobalConfig.Connection.CreateTeam(team);

                    return RedirectToAction(nameof(Index));
                }

                TeamMVCModel input = new TeamMVCModel();
                var people = GlobalConfig.Connection.GetAllPeople();

                input.TeamMembers = people.Select(p => new SelectListItem()
                {
                    Text = p.FullName,
                    Value = p.Id.ToString()
                }).ToList();
                return View(input);
            }
            catch
            {
                return View();
            }
        }
    }
}

MVCUI/Controllers/TournamentsController.cs
using MVCUI.Models;
using System.Linq;
using System.Web.Mvc;
using TournamentTracker;
using TrackerLibrary;
using TrackerLibrary.Models;

namespace MVCUI.Controllers
{
    public class TournamentsController : Controller
    {
        public ActionResult Index()
        {
            return RedirectToAction("Index", "Home");
        }

        public ActionResult Create()
        {
            var teams = GlobalConfig.Connection.GetAllTeams();
            var prizes = GlobalConfig.Connection.GetAllPrizes();

            TournamentMVCModel tournamentMVC = new TournamentMVCModel()
            {
                EnteredTeams = teams.Select(t => new SelectListItem
                {
                    Value = t.Id.ToString(),
                    Text = t.TeamName
                }).ToList(),

                Prizes = prizes.Select(p => new SelectListItem
                {
                    Value = p.Id.ToString(),
                    Text = p.PlaceName
                }).ToList()
            };

            return View(tournamentMVC);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(TournamentMVCModel tournamentMVC)
        {
            try
            {
                if (tournamentMVC.SelectedEnteredTeams.Count <= 0)
                {
                    ModelState.AddModelError(nameof(tournamentMVC.SelectedEnteredTeams.Count), "Invalid selected teams count");
                }

                if (tournamentMVC.SelectedPrizes.Count <= 0)
                {
                    ModelState.AddModelError(nameof(tournamentMVC.SelectedPrizes.Count), "Invalid selected prizes count");
                }

                if (ModelState.IsValid)
                {
                    TournamentModel tournament = new TournamentModel()
                    {
                        TournamentName = tournamentMVC.TournamentName,
                        EntryFee = tournamentMVC.EntryFee,
                        EnteredTeams = tournamentMVC.SelectedEnteredTeams.Select(e => new TeamModel { Id = int.Parse(e) }).ToList(),
                        Prizes = tournamentMVC.SelectedPrizes.Select(p => new PrizeModel { Id = int.Parse(p) }).ToList()
                    };

                    TournamentLogic.CreateRounds(tournament);

                    GlobalConfig.Connection.CreateTournament(tournament);

                    tournament.AlertUsersToNewRound();

                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    return View();
                }
            }
            catch
            {
                return View();
            }
        }
    }
}

MVCUI/Views/Home/Index.cshtml
@model IEnumerable<TrackerLibrary.Models.TournamentModel>

@{
    ViewBag.Title = "Home Page";
}

<div class="row">
    <div class="col-md-8">
        <div class="jumbotron">
            <h1>Office Fun!</h1>
            <p class="lead">Track your in-office tournaments easily and have a great time doing it.</p>
            <p>@Html.ActionLink("Create a Tournament", "Create", "Tournaments", new { area = "" }, new { @class = "btn btn-primary btn-lg" })</p>
        </div>

        <div class="row">
            <div class="col-md-6">
                <h2>Play with friends</h2>
                <p>
                    Get a team and get started today on a new tournament.
                </p>
            </div>
            <div class="col-md-6">
                <h2>Win prizes</h2>
                <p>Set up a tournament with prizes for first and second place and compete to win.</p>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <h2>Current Tournaments</h2>
        <ul class="list-unstyled tourney-display">
            @foreach (var tournament in Model)
                {
                    <li><a>@tournament.TournamentName</a></li>
                }
        </ul>
    </div>
</div>

MVCUI/Views/People/Create.cshtml
@model TrackerLibrary.Models.PersonModel

@{
    ViewBag.Title = "Create";
}

<h2>Create New Person</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmailAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmailAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmailAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CellphoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CellphoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CellphoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")    
}

MVCUI/Views/People/Index.cshtml
@model IEnumerable<TrackerLibrary.Models.PersonModel>

@{
    ViewBag.Title = "Index";
}

<h2>View All People</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EmailAddress)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CellphoneNumber)
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EmailAddress)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CellphoneNumber)
        </td>
    </tr>
}

</table>

MVCUI/Views/Prizes/Create.cshtml
@model TrackerLibrary.Models.PrizeModel

@{
    ViewBag.Title = "Create";
}

<h2>Create New Prize</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.PlaceNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PlaceNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PlaceNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PlaceName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PlaceName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PlaceName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PrizeAmount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PrizeAmount, new { htmlAttributes = new { @class = "form-control", @Value = 0 } })
                @Html.ValidationMessageFor(model => model.PrizeAmount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PrizePercentage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PrizePercentage, new { htmlAttributes = new { @class = "form-control", @Value = 0 } })
                @Html.ValidationMessageFor(model => model.PrizePercentage, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVCUI/Views/Prizes/Index.cshtml
@model IEnumerable<TrackerLibrary.Models.PrizeModel>

@{
    ViewBag.Title = "Index";
}

<h2>View All Prizes</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.PlaceNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PlaceName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PrizeAmount)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PrizePercentage)
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.PlaceNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PlaceName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PrizeAmount)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PrizePercentage)
        </td>
    </tr>
}

</table>

MVCUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Tournament Tracker</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Tournament Tracker", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("People", "Index", "People")</li>
                    <li>@Html.ActionLink("Teams", "Index", "Teams")</li>
                    <li>@Html.ActionLink("Prizes", "Index", "Prizes")</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Tournament Tracker Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

</body>
</html>

MVCUI/Views/Tournaments/Create.cshtml
@model MVCUI.Models.TournamentMVCModel

@{
    ViewBag.Title = "Create";
}

<h2>Create New Tournament</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="">
    <hr />
    <div class="col-md-4">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.TournamentName, htmlAttributes: new { @class = "control-label" })
            <div class="">
                @Html.EditorFor(model => model.TournamentName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TournamentName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EntryFee, htmlAttributes: new { @class = "control-label" })
            <div class="">
                @Html.EditorFor(model => model.EntryFee, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EntryFee, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="form-group">
            @Html.LabelFor(model => model.EnteredTeams, htmlAttributes: new { @class = "control-label" })
            <div class="">
                @foreach (var team in Model.EnteredTeams)
                {
                    <div class="checkbox">
                        <label>
                            <input type="checkbox" name="SelectedEnteredTeams" value="@team.Value" /> @team.Text
                        </label>
                    </div>
                }
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="form-group">
            @Html.LabelFor(model => model.Prizes, htmlAttributes: new { @class = "control-label" })
            <div class="">
                @foreach (var prize in Model.Prizes)
                {
                    <div class="checkbox">
                        <label>
                            <input type="checkbox" name="SelectedPrizes" value="@prize.Value" /> @prize.Text
                        </label>
                    </div>
                }
            </div>
        </div>
    </div>

</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}